name: Publish Timestamped Snapshot Artifacts

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish-ballerina-lang:
    name: Build and Publish Ballerina Lang
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ballerina-platform'
    steps:
      -   name: Checkout Repository
          uses: actions/checkout@v2

      -   name: Set up JDK 11
          uses: actions/setup-java@v1
          with:
            java-version: 11

      -   name: Initialize Sub Modules
          run: git submodule update --init

      -   name: Change to Timestamped Version
          run: |
            startTime=$(TZ="Asia/Kolkata" date +'%Y%m%d-%H%M00')
            latestCommit=$(git log -n 1 --pretty=format:"%h")
            VERSION=$((grep -w 'version' | cut -d= -f2) < gradle.properties | rev | cut --complement -d- -f1 | rev)
            updatedVersion=$VERSION-$startTime-$latestCommit
            echo $updatedVersion
            sed -i "s/version=\(.*\)/version=$updatedVersion/g" gradle.properties

      -   name: Build and Publish
          env:
            packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
            packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
          run: |
            ./gradlew clean build publish -x createJavadoc --scan --continue --rerun-tasks
            ./gradlew createCodeCoverageReport

      -   name: Generate Codecov Report
          uses: codecov/codecov-action@v1
          with:
            files: ./.jacoco/reports/jacoco/report.xml

      -   name: Trigger Standard Library Module Builds
          run: |
            echo "Triggering stdlib module builds"
            curl --request \
            POST 'https://api.github.com/repos/ballerina-platform/ballerina-standard-library/dispatches' \
            --header 'Accept: application/vnd.github.v3+json' \
            --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "event_type": "ballerina-lang-push"
            }'
